In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt

import pandas as pd
import seaborn as sns

'''tensorflow: Machine learning library.
matplotlib.pyplot: Plotting/visualization tool.
pandas: Data manipulation library.
seaborn: Enhanced data visualization.'''

'tensorflow: Machine learning library.\nmatplotlib.pyplot: Plotting/visualization tool.\npandas: Data manipulation library.\nseaborn: Enhanced data visualization.'

In [2]:
#training image preprocessing
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 70295 files belonging to 38 classes.


In [3]:
'''
directory: Folder with data; if labels are "inferred", it must contain class subfolders.
labels: Options are "inferred" (from directory), None (no labels), or a custom label list matching files.
label_mode: Label encoding as "int", "categorical", "binary", or None.
class_names: Custom class order (used with inferred labels).
color_mode: Image color format - "grayscale", "rgb", or "rgba".
batch_size: Data batch size, default is 32; None yields individual samples.
image_size: Resized image dimensions, defaults to (256, 256).
shuffle: Whether to shuffle data (default: True).
seed: Random seed for shuffling.
validation_split: Data fraction for validation.
subset: "training", "validation", or "both" (used with validation_split).
interpolation: Resizing method (e.g., "bilinear").
follow_links: Follow symbolic links to subdirectories.
crop_to_aspect_ratio/pad_to_aspect_ratio: Resize while preserving aspect ratio, with cropping or padding.
data_format: "channel_last" or "channel_first".
verbose: Show class and file count (default: True).
'''

'\ndirectory: Folder with data; if labels are "inferred", it must contain class subfolders.\nlabels: Options are "inferred" (from directory), None (no labels), or a custom label list matching files.\nlabel_mode: Label encoding as "int", "categorical", "binary", or None.\nclass_names: Custom class order (used with inferred labels).\ncolor_mode: Image color format - "grayscale", "rgb", or "rgba".\nbatch_size: Data batch size, default is 32; None yields individual samples.\nimage_size: Resized image dimensions, defaults to (256, 256).\nshuffle: Whether to shuffle data (default: True).\nseed: Random seed for shuffling.\nvalidation_split: Data fraction for validation.\nsubset: "training", "validation", or "both" (used with validation_split).\ninterpolation: Resizing method (e.g., "bilinear").\nfollow_links: Follow symbolic links to subdirectories.\ncrop_to_aspect_ratio/pad_to_aspect_ratio: Resize while preserving aspect ratio, with cropping or padding.\ndata_format: "channel_last" or "chann

In [4]:
#validation image preprocessing
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)


Found 17572 files belonging to 38 classes.


In [5]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [6]:
validation_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [7]:
print(training_set.class_names)
print(validation_set.class_names)

['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Sp

In [8]:
for x,y in training_set:
    print(x, x.shape) #x content
    print(y, y.shape) #y content
    break

tf.Tensor(
[[[[182.   178.   175.  ]
   [180.   176.   173.  ]
   [197.5  193.5  190.5 ]
   ...
   [189.5  184.5  180.5 ]
   [191.75 186.75 182.75]
   [188.25 183.25 179.25]]

  [[207.   203.   200.  ]
   [201.75 197.75 194.75]
   [184.25 180.25 177.25]
   ...
   [196.5  191.5  187.5 ]
   [194.5  189.5  185.5 ]
   [192.75 187.75 183.75]]

  [[193.25 189.25 186.25]
   [195.25 191.25 188.25]
   [201.75 197.75 194.75]
   ...
   [192.5  187.5  183.5 ]
   [203.25 198.25 194.25]
   [187.   182.   178.  ]]

  ...

  [[159.25 148.25 144.25]
   [155.25 144.25 140.25]
   [162.   151.   147.  ]
   ...
   [161.75 150.75 144.75]
   [162.75 151.75 145.75]
   [161.75 150.75 144.75]]

  [[171.5  160.5  156.5 ]
   [162.25 151.25 147.25]
   [172.   161.   157.  ]
   ...
   [162.75 151.75 145.75]
   [166.25 155.25 149.25]
   [161.75 150.75 144.75]]

  [[155.   144.   140.  ]
   [169.75 158.75 154.75]
   [163.   152.   148.  ]
   ...
   [162.   151.   145.  ]
   [160.5  149.5  143.5 ]
   [157.   146.   14

In [9]:
'''
To avoid Overshooding
1. Choose small learning rate default 0.001 we are taking 0.0001
2. There may be chance of Underfitting so increase number of neurons 0.0001
3. Add more convolution layer extract more feature from images there may be possibly that model unable 
to capture relevent feature or model is confusing due to lack of feature so feed with more feature.
'''

'\nTo avoid Overshooding\n1. Choose small learning rate default 0.001 we are taking 0.0001\n2. There may be chance of Underfitting so increase number of neurons 0.0001\n3. Add more convolution layer extract more feature from images there may be possibly that model unable \nto capture relevent feature or model is confusing due to lack of feature so feed with more feature.\n'

In [10]:
##Building Model

In [11]:
cnn = tf.keras.Sequential() # allows you to build a neural network by stacking layers sequentially, one after another

In [12]:
##Building Convolutional Layer1
cnn.add(tf.keras.layers.Input(shape=[128, 128, 3]))

# Add the rest of the layers
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [13]:
cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [14]:
cnn.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [15]:
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [16]:
cnn.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [17]:
cnn.add(tf.keras.layers.Dropout(0.25)) #cut layers 25% for reduse overfitting

In [18]:
cnn.add(tf.keras.layers.Flatten()) #2D - 1D

In [19]:
cnn.add(tf.keras.layers.Dense(units=1500,activation='relu'))

In [20]:
cnn.add(tf.keras.layers.Dropout(0.4))

In [21]:
#output layer
cnn.add(tf.keras.layers.Dense(units=38,activation='softmax'))

In [22]:
#compiling model
cnn.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

#Adam is an adaptive learning rate optimization algorithm that adjusts the learning rate during training for efficient convergence. It’s widely used due to its speed and performance.
#compares the model’s output probabilities with the true labels and computes the error.
#calculating the percentage of correct predictions.

In [23]:
cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 63, 63, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                    

In [ ]:
#model training
training_history = cnn.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
 176/2197 [=>............................] - ETA: 18:27 - loss: 3.2717 - accuracy: 0.1152